name = "medium"
compatibility_date = "2024-07-30"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODMzYmEyNGEtNTViOC00NTMxLTk1MzYtODQ4YTdlZGRjY2EyIiwidGVuYW50X2lkIjoiOGJjMTYxNmEwZWI0YzdhMDNkNTk4NDQyNTdlZTg0NWUwNDg1YzNkY2I4YzAzOWQ4ZWJhMzY4Njc2ZWU4NzUzNiIsImludGVybmFsX3NlY3JldCI6ImQwODNkYTRhLTg3ZjAtNDhkZS04MmJhLTVhMWE0MDEwN2MxMSJ9.D8jBounjY_XDvRvH-NQfJ7rX1EfK9jSVQLh2Sje5fsw"
JWT_SECRET="a123456"

